import { isUnknownRecord, unknownField, errorCode, errorMessage } from "../../pcr-core/src/types.ts";
import type { UnknownRecord } from "../../pcr-core/src/types.ts";
import type { BackendSnapshotManifest, BackendViewerObject, BackendViewerActive, SnapshotObjectIdentity, SnapshotSource, SnapshotCapture, SnapshotHistoryHead, SnapshotHistoryEntry, SnapshotCoordinate, SnapshotCatalogScope, SnapshotValidationSummary, RefMap, SnapshotObjectKind } from "./snapshot-types.ts";
export { unknownField as field, errorCode, errorMessage };
export function object(value:unknown,label="Viewer data"):UnknownRecord {if(!isUnknownRecord(value))throw new TypeError(`${label} must be an object.`);return value;}
export function list(value:unknown,label="Viewer data"):unknown[] {if(!Array.isArray(value))throw new TypeError(`${label} must be an array.`);return value;}
export function objects(value:unknown,label="Viewer data"):UnknownRecord[] {const items=list(value,label);if(!items.every(isUnknownRecord))throw new TypeError(`${label} must contain objects.`);return items;}
export function text(value:unknown,label="Viewer data"):string {if(typeof value!=="string")throw new TypeError(`${label} must be a string.`);return value;}
export function numeric(value:unknown,label="Viewer data"):number {if(typeof value!=="number")throw new TypeError(`${label} must be a number.`);return value;}
export function strings(value:unknown):string[] {const values=list(value);if(!values.every((item):item is string=>typeof item==="string"))throw new TypeError("Viewer values must be strings.");return values;}
export function json(bytes:Buffer|string):unknown {const value:unknown=JSON.parse(typeof bytes==="string"?bytes:bytes.toString("utf8"));return value;}
export function refMap(value:unknown):RefMap {const map=object(value);if(!Object.values(map).every((ref):ref is string=>typeof ref==="string"))throw new TypeError("Viewer refs must be strings.");return Object.fromEntries(Object.entries(map).map(([key,ref])=>[key,text(ref)]));}
export function coordinate(value:unknown):SnapshotCoordinate {const data=object(value);return {system:text(data.system),version:text(data.version)};}
export function source(value:unknown):SnapshotSource {const data=object(value);return {catalog:text(data.catalog),aliases:text(data.aliases),coverage:objects(data.coverage).map(row=>({coordinate:coordinate(row.coordinate),ref:text(row.ref)})),release_revision_markers:refMap(data.release_revision_markers)};}
export function capture(value:unknown):SnapshotCapture {const data=object(value);if(data.validation_state!=="validated")throw new TypeError("Viewer capture must be validated.");return {source_ref:text(data.source_ref),integration_commit:text(data.integration_commit),base_commit:text(data.base_commit),tree_hash:text(data.tree_hash),validation_state:data.validation_state,ui_bundle_ref:text(data.ui_bundle_ref)};}
export function identity(value:unknown):SnapshotObjectIdentity {const data=object(value);return {generator_contract_sha256:text(data.generator_contract_sha256),schema_contract_sha256:text(data.schema_contract_sha256),source_fingerprint:text(data.source_fingerprint),release_revision_marker:data.release_revision_marker===null?null:text(data.release_revision_marker)};}
const objectKinds:ReadonlySet<string>=new Set(["ui_bundle","pcr_detail","catalog_entry","alias_entry","catalog_shard","catalog_root","alias_shard","alias_root","coverage_entry","coverage_shard","coverage_root","history_page"]);
function objectKind(value:unknown):value is SnapshotObjectKind {return typeof value==="string" && objectKinds.has(value);}
/** Called after the actual schema registry check; this also proves the TS fields. */
export function viewerObject(value:unknown):BackendViewerObject {const data=object(value);if(data.schema_version!==1 || !objectKind(data.object_kind))throw new TypeError("Invalid Viewer object header.");return {schema_version:data.schema_version,object_kind:data.object_kind,identity:identity(data.identity),entry:data.entry};}
export function validationSummary(value:unknown):SnapshotValidationSummary {const data=object(value);if(data.status!=="passed")throw new TypeError("Viewer validation summary must pass.");return {status:data.status,checks:numeric(data.checks)};}
export function catalogScope(value:unknown):SnapshotCatalogScope {if(value!=="material"&&value!=="all"&&value!=="legacy")throw new TypeError("Invalid Viewer catalog scope.");return value;}
export function manifest(value:unknown):BackendSnapshotManifest {
 const data=object(value),counts=object(data.counts),refs=object(data.refs),lineage=object(data.lineage);
 if(data.schema_version!==1||data.kind!=="viewer-snapshot-manifest")throw new TypeError("Invalid Viewer manifest header.");
 return {schema_version:data.schema_version,kind:data.kind,snapshot_id:text(data.snapshot_id),goal_id:text(data.goal_id),harness_snapshot_id:text(data.harness_snapshot_id),captured_at:text(data.captured_at),validated_at:text(data.validated_at),validation_summary:validationSummary(data.validation_summary),catalog_scope:catalogScope(data.catalog_scope),previous_snapshot_id:data.previous_snapshot_id===null?null:text(data.previous_snapshot_id),previous_manifest_ref:data.previous_manifest_ref===null?null:text(data.previous_manifest_ref),sequence:numeric(data.sequence),generator_version:text(data.generator_version),generator_contract_sha256:text(data.generator_contract_sha256),schema_contract_sha256:text(data.schema_contract_sha256),source:source(data.source),capture:capture(data.capture),predecessor:data.predecessor===null?null:text(data.predecessor),lineage:{renames:refMap(lineage.renames)},counts:{pcr:numeric(counts.pcr),alias:numeric(counts.alias),coverage:numeric(counts.coverage),catalog_shards:numeric(counts.catalog_shards),alias_shards:numeric(counts.alias_shards),coverage_shards:numeric(counts.coverage_shards)},refs:{pcr_entries:refMap(refs.pcr_entries),alias_entries:refMap(refs.alias_entries),coverage_entries:refMap(refs.coverage_entries),catalog_shards:refMap(refs.catalog_shards),alias_shards:refMap(refs.alias_shards),coverage_shards:refMap(refs.coverage_shards),catalog_root:text(refs.catalog_root),alias_root:text(refs.alias_root),coverage_root:text(refs.coverage_root)}};
}
export function historyHead(value:unknown):SnapshotHistoryHead {const data=object(value);if(data.schema_version!==1||data.kind!=="viewer-history-head")throw new TypeError("Invalid Viewer history head.");return {schema_version:data.schema_version,kind:data.kind,page_ref:text(data.page_ref),latest_sequence:numeric(data.latest_sequence)};}
export function historyEntry(value:unknown):SnapshotHistoryEntry {const data=object(value);return {sequence:numeric(data.sequence),manifest_ref:text(data.manifest_ref)};}
export function active(value:unknown):BackendViewerActive {const data=object(value);if(data.schema_version!==1||data.kind!=="viewer-active"||data.cache_version!==1||data.validation_state!=="validated")throw new TypeError("Invalid Viewer active pointer.");return {schema_version:data.schema_version,kind:data.kind,snapshot_id:text(data.snapshot_id),snapshot_url:text(data.snapshot_url),snapshot_hash:text(data.snapshot_hash),manifest_ref:text(data.manifest_ref),sequence:numeric(data.sequence),cache_version:data.cache_version,ui_bundle_ref:text(data.ui_bundle_ref),validation_state:data.validation_state};}
